name: Updater

on:
  push:
    branches:
      - main
  schedule:
    # Run every day at 00:00 UTC
    - cron: '0 0 * * *'
  # Allow manual running as well
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: oven-sh/setup-bun@v1
      - run: bun install
        name: Install dependencies
      - run: bun run src/index.ts
        name: Update things
        env:
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
          CURSEFORGE_TOKEN: ${{ secrets.CURSEFORGE_TOKEN }}
      # Commit any changes back to the project
      - name: Commit changes
        env:
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
        run: |
          git config --global user.email "michaelhillcox@gmail.com"
          git config --global user.name "Michael Hillcox"
          git add .
          git commit -a -m "Update things"
      - name: Push updates
        uses: ad-m/github-push-action@master
        with:
          branch: ${{ github.ref }}